// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TO.Persistence;

namespace TO.Persistence.Migrations
{
    [DbContext(typeof(TODBContext))]
    [Migration("20181116210722_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("TO.Domain.Entities.AttributeType", b =>
                {
                    b.Property<int>("AttributeTypeId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AttributeTypeName");

                    b.Property<string>("Type");

                    b.HasKey("AttributeTypeId");

                    b.ToTable("AttributeTypes");
                });

            modelBuilder.Entity("TO.Domain.Entities.AttributeValue", b =>
                {
                    b.Property<int>("AttributeValueId")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ObjectItemId");

                    b.Property<string>("Value");

                    b.HasKey("AttributeValueId");

                    b.HasIndex("ObjectItemId");

                    b.ToTable("AttributeValues");
                });

            modelBuilder.Entity("TO.Domain.Entities.Interface", b =>
                {
                    b.Property<int>("InterfaceId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("InterfaceName");

                    b.HasKey("InterfaceId");

                    b.ToTable("Interfaces");
                });

            modelBuilder.Entity("TO.Domain.Entities.ObjectItem", b =>
                {
                    b.Property<int>("ObjectItemId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("InterfaceId");

                    b.Property<string>("ObjectItemName");

                    b.HasKey("ObjectItemId");

                    b.HasIndex("InterfaceId");

                    b.ToTable("ObjectItems");
                });

            modelBuilder.Entity("TO.Domain.Entities.AttributeValue", b =>
                {
                    b.HasOne("TO.Domain.Entities.ObjectItem")
                        .WithMany("Attributes")
                        .HasForeignKey("ObjectItemId");
                });

            modelBuilder.Entity("TO.Domain.Entities.ObjectItem", b =>
                {
                    b.HasOne("TO.Domain.Entities.Interface", "Interface")
                        .WithMany()
                        .HasForeignKey("InterfaceId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
